# ====================================================================
# Docker Compose Override for Development Environment
# Version: 1.0
# ====================================================================
# This file is automatically merged with docker-compose.yml by Docker Compose.
# It modifies the configuration for a local development setup.

version: '3.8'

services:
  # -------------------------------------------------
  # 1. Override the Node-RED Service
  # -------------------------------------------------
  nodered:
    # By re-declaring the volumes, we ensure that our local folder is always used,
    # making development changes (like editing a function node) instant.
    volumes:
      - ./node-red:/data

  # -------------------------------------------------
  # 2. Override the Web Server Service
  # -------------------------------------------------
  web_server:
    # Re-declaring volumes here ensures that any changes to your HTML, CSS, JS,
    # or image files are immediately served by Nginx without a restart.
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
      - ./artistic-resources:/usr/share/nginx/html/artistic-resources
