version: '3.8'

services:
  nodered:
    volumes:
      - ./node-red/flows.json:/data/flows.json
      - ./node-red/settings.js:/data/settings.js
    entrypoint: []
    command: ["npm", "start", "--", "--userDir", "/data"]

  python_api:
    volumes:
      - ./python-api:/app
      - ./backend:/app/backend
    environment:
      - MODEL_DIR=/app/backend/models

  web_server:
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./artistic-resources:/usr/share/nginx/html/artistic-resources
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
